version: '3.7'

services:

  rabbitmq:
    image: rabbitmq:3-management
    deploy:
      mode: global
      placement:
        constraints: [node.labels.mautic == true]    
    environment:
      - RABBITMQ_DEFAULT_VHOST=mautic
    volumes: 
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - mautic-net
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # RabbitMQ Management UI      

  smtprelay:
    image: mwader/postfix-relay
    hostname: mauticsmtp
    environment:
      - POSTFIX_myhostname=mailing.smartoys.be
      - OPENDKIM_DOMAINS=gameo.com dlgamer.com smartoys.be r6g.eu
    networks:
      - mautic-net
    deploy:
      mode: global
      placement:
        constraints: [node.labels.mauticdb == true]
    volumes:
      - mautic_opendkim_keys:/etc/opendkim/keys
    restart: always

  mauticdb:
    image: mysql:8.0
    hostname: mauticdb
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      mode: global
      placement:
        constraints: [node.labels.mauticdb == true]
   # don't expose if not needed
#      resources:
#        reservations:
#          memory: 16G
#          cpus: '7.0'
    environment:
      - MYSQL_ROOT_PASSWORD=g9uL5mCWTk1YIq92
    command:
      - --slow_query_log=1
      - --slow_query_log_file=/var/log/mysql/mysql-slow.log
      - --long_query_time=1
      - --sql-mode=STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION   
    networks:
      - mautic-net
    ports:
      - 3306:3306      

  mautic_smartoys:
    image: mautic/mautic:5.2.1-apache
    hostname: mautic_smartoys
    links:
      - mauticdb:mysql
    depends_on:
      - mauticdb
      - smtprelay
    volumes: 
      - mautic_smartoys_config:/var/www/html/config
      - mautic_smartoys_logs:/var/www/html/var/logs
      - mautic_smartoys_files:/var/www/html/docroot/media/files
      - mautic_smartoys_images:/var/www/html/docroot/media/images
      - mautic_smartoys_cron:/opt/mautic/cron
    deploy:
      mode: global
      placement:
        constraints: [node.labels.mautic == true]
#      resources:
#        reservations:
#          memory: 6G
#          cpus: '3.0'
      labels:
        - "traefik.enable=true"
    #   - "traefik.http.routers.mautic.tls=true"
        - "traefik.http.middlewares.mautic.compress=true"

        - "traefik.http.middlewares.mautic-redirect-websecure.redirectscheme.scheme=https"
        - "traefik.http.routers.mautic.middlewares=mautic-redirect-websecure"
        - "traefik.http.routers.mautic.rule=Host(`mailing.smartoys.be`, `mautic.smartoys.be` )"
        - "traefik.http.routers.mautic.entrypoints=web"

        - "traefik.http.routers.mautic-secure.rule=Host(`mailing.smartoys.be`, `mautic.smartoys.be`)"
        - "traefik.http.routers.mautic-secure.entrypoints=websecure"
        - "traefik.http.routers.mautic-secure.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.mautic.loadbalancer.server.port=80"
    environment:
      - MAUTIC_DB_HOST=mauticdb
      - MYSQL_PORT_3306_TCP=3306
      - MAUTIC_DB_USER=root
      - MAUTIC_DB_PASSWORD=g9uL5mCWTk1YIq92
      - MAUTIC_DB_NAME=mailing
      - MAUTIC_CONFIG_DEBUG=1
      - MAUTIC_TRUSTED_PROXIES=["0.0.0.0/0"]       
      - PHP_INI_VALUE_MEMORY_LIMIT=5G
      - PHP_INI_VALUE_MAX_EXECUTION_TIME=3600
      - PHP_INI_VALUE_LOG_ERRORS = On
      - PHP_INI_VALUE_ERROR_LOG=/dev/stdout
    networks:
    # internal network for mysql
      - mautic-net
    # external network for reverse proxy
      - traefik-public

  mautic_smartoys_cron:
    image: mautic/mautic:5.2.1-apache
    hostname: mautic_smartoys_cron
    links:
      - mauticdb:mysql
    depends_on:
      - mauticdb
      - smtprelay
    volumes: 
      - mautic_smartoys_config:/var/www/html/config
      - mautic_smartoys_cron_logs:/var/www/html/var/logs
      - mautic_smartoys_files:/var/www/html/docroot/media/files
      - mautic_smartoys_images:/var/www/html/docroot/media/images
      - mautic_smartoys_cron:/opt/mautic/cron
    deploy:
      mode: global
      placement:
        constraints: [node.labels.mautic == true]
    environment:
      - MAUTIC_DB_HOST=mauticdb
      - MYSQL_PORT_3306_TCP=3306
      - MAUTIC_DB_USER=root
      - MAUTIC_DB_PASSWORD=g9uL5mCWTk1YIq92
      - MAUTIC_DB_NAME=mailing
      - MAUTIC_CONFIG_DEBUG=1
      - MAUTIC_TRUSTED_PROXIES=["0.0.0.0/0"]
      - MAUTIC_MESSENGER_DSN_EMAIL="amqp://guest:guest@rabbitmq:5672/mautic/messages"
      - MAUTIC_MESSENGER_DSN_HIT="amqp://guest:guest@rabbitmq:5672/mautic/messages"      
      - PHP_INI_VALUE_MEMORY_LIMIT=5G
      - PHP_INI_VALUE_MAX_EXECUTION_TIME=3600
      - PHP_INI_VALUE_LOG_ERRORS = On
      - PHP_INI_VALUE_ERROR_LOG=/dev/stdout
      - DOCKER_MAUTIC_ROLE=mautic_cron      
      
    networks:
    # internal network for mysql
      - mautic-net   

  mautic_smartoys_worker:
    image: mautic/mautic:5.2.1-apache
    hostname: mautic_smartoys_worker
    links:
      - mauticdb:mysql
    depends_on:
      - mauticdb
      - smtprelay
    volumes: 
      - mautic_smartoys_config:/var/www/html/config
      - mautic_smartoys_worker_logs:/var/www/html/var/logs
      - mautic_smartoys_files:/var/www/html/docroot/media/files
      - mautic_smartoys_images:/var/www/html/docroot/media/images
      - mautic_smartoys_cron:/opt/mautic/cron
    deploy:
      mode: global
      placement:
        constraints: [node.labels.mautic == true]
    environment:
      - DOCKER_MAUTIC_ROLE=mautic_worker
      - MAUTIC_DB_HOST=mauticdb
      - MYSQL_PORT_3306_TCP=3306
      - MAUTIC_DB_USER=root
      - MAUTIC_DB_PASSWORD=g9uL5mCWTk1YIq92
      - MAUTIC_DB_NAME=mailing
      - MAUTIC_CONFIG_DEBUG=1
      - MAUTIC_TRUSTED_PROXIES=["0.0.0.0/0"]
      - MAUTIC_MESSENGER_DSN_EMAIL=amqp://guest:guest@rabbitmq:5672/mautic/messages
      - MAUTIC_MESSENGER_DSN_HIT=amqp://guest:guest@rabbitmq:5672/mautic/messages
      - PHP_INI_VALUE_MEMORY_LIMIT=5G
      - PHP_INI_VALUE_MAX_EXECUTION_TIME=3600
      - PHP_INI_VALUE_LOG_ERRORS = On
      - PHP_INI_VALUE_ERROR_LOG=/dev/stdoutt
    networks:
    # internal network for mysql
      - mautic-net 

  mautic_dlgamer:
    image: mautic/mautic:v4
    hostname: mautic_dlgamer
    links:
      - mauticdb:mysql
    depends_on:
      - mauticdb
      - smtprelay
    volumes:
      - mautic_data_dlgamer:/var/www/html
    deploy:
      mode: global
  #    resources:
  #      reservations:
  #        memory: 6G
  #        cpus: '3.0'
      placement:
        constraints: [node.labels.mautic == true]
      labels:
        - "traefik.enable=true"
    #   - "traefik.http.routers.mautic_dlgamer_com.tls=true"
        - "traefik.http.middlewares.mautic_dlgamer_com.compress=true"

        - "traefik.http.middlewares.mautic_dlgamer_com-redirect-websecure.redirectscheme.scheme=https"
        - "traefik.http.routers.mautic_dlgamer_com.middlewares=mautic_dlgamer_com-redirect-websecure"
        - "traefik.http.routers.mautic_dlgamer_com.rule=Host(`mailing.dlgamer.com`, `mautic.dlgamer.com`)"
        - "traefik.http.routers.mautic_dlgamer_com.entrypoints=web"

        - "traefik.http.routers.mautic_dlgamer_com-secure.rule=Host(`mailing.dlgamer.com`, `mautic.dlgamer.com`)"
        - "traefik.http.routers.mautic_dlgamer_com-secure.entrypoints=websecure"
        - "traefik.http.routers.mautic_dlgamer_com-secure.tls.certresolver=letsencryptresolver"

        - "traefik.http.services.mautic_dlgamer_com.loadbalancer.server.port=80"

    environment:
      - MAUTIC_DB_HOST=mauticdb
      - MYSQL_PORT_3306_TCP=3306
      - MAUTIC_DB_USER=root
      - MAUTIC_DB_PASSWORD=g9uL5mCWTk1YIq92
      - MAUTIC_DB_NAME=mautic_dlgamer_com
      - MAUTIC_RUN_CRON_JOBS=true
      - PHP_MEMORY_LIMIT=3G
      - PHP_MAX_EXECUTION_TIME=3600
      - MAUTIC_CONFIG_DEBUG=1
      #- MAUTIC_TRUSTED_PROXIES=0.0.0.0/0
    networks:
    # internal network for mysql
      - mautic-net
    # external network for reverse proxy
      - traefik-public

  mautic_gameo:
    image: mautic/mautic:v4
    hostname: mautic_gameo
    links:
      - mauticdb:mysql
    depends_on:
      - mauticdb
      - smtprelay
    volumes:
      - mautic_data_gameo:/var/www/html
    deploy:
      mode: global
 #     resources:
 #       reservations:
 #         memory: 6G
 #         cpus: '3.0'
      placement:
        constraints: [node.labels.mautic == true]
      labels:
        - "traefik.enable=true"
    #   - "traefik.http.routers.mautic_gameo_com.tls=true"
        - "traefik.http.middlewares.mautic_gameo_com.compress=true"

        - "traefik.http.middlewares.mautic_gameo_com-redirect-websecure.redirectscheme.scheme=https"
        - "traefik.http.routers.mautic_gameo_com.middlewares=mautic_gameo_com-redirect-websecure"
        - "traefik.http.routers.mautic_gameo_com.rule=Host(`mailing.gameo.com`, `mautic.gameo.com`)"
        - "traefik.http.routers.mautic_gameo_com.entrypoints=web"

        - "traefik.http.routers.mautic_gameo_com-secure.rule=Host(`mailing.gameo.com`, `mautic.gameo.com`)"
        - "traefik.http.routers.mautic_gameo_com-secure.entrypoints=websecure"
        - "traefik.http.routers.mautic_gameo_com-secure.tls.certresolver=letsencryptresolver"

        - "traefik.http.services.mautic_gameo_com.loadbalancer.server.port=80"

    environment:
      - MAUTIC_DB_HOST=mauticdb
      - MYSQL_PORT_3306_TCP=3306
      - MAUTIC_DB_USER=root
      - MAUTIC_DB_PASSWORD=g9uL5mCWTk1YIq92
      - MAUTIC_DB_NAME=mautic_gameo_com
      - MAUTIC_RUN_CRON_JOBS=true
      #- MAUTIC_TRUSTED_PROXIES=0.0.0.0/0
    networks:
    # internal network for mysql
      - mautic-net
    # external network for reverse proxy
      - traefik-public



volumes:
  rabbitmq-data:
    driver: local 
  mysql_data:
    driver: local
  mautic_data:
    driver: local
  mautic_data_smartoys:
    driver: local    
  mautic_data_dlgamer:
    driver: local
  mautic_data_gameo:
    driver: local
  mautic_opendkim_keys:
    driver: local
  mautic_opendkim_keys_dlgamer:
    driver: local
  mautic_opendkim_keys_gameo:
    driver: local
  # Subfolders for "mautic_smartoys"
  mautic_smartoys_config:
    driver: local
  mautic_smartoys_logs:
    driver: local
  mautic_smartoys_files:
    driver: local
  mautic_smartoys_images:
    driver: local
  mautic_smartoys_cron:
    driver: local    
  # Subfolders for "mautic_smartoys_worker"
  mautic_smartoys_worker_logs:
    driver: local
  # Subfolders for "mautic_smartoys_cron"
  mautic_smartoys_cron_logs:
    driver: local


configs:
  mysqldv3.cnf:
    external: true


networks:
  mautic-net:
    external: true
  traefik-public:
    external: true